import { combineReducers } from "redux";

import bottom_nav from "./bottom_nav";
import dark_mode from "./dark_mode";
import {
    AddFeedSwitchReducer,
    AddFeedTodoDescReducer,
    AddFeedStepsReducer,
    AddFeedListReducer,
    AddFeedDueDateReducer,
    AddFeedRemindReducer,
    AddFeedRepeatReducer,
    AddFeedNotesReducer,
    AddFeedSummaryReducer,
    AddFeedListSelectedReducer,
    AddTodosReducer,
    AddGoalsReducer,
    AddFeedCompleteSetReducer,
    AddFeedImportantSetReducer,
    AddFeedTextareaReducer,
    GoalsFeedReducer,
    AddFeedFocusTimeReducer,
    AddFeedURLReducer,
    UsersListsReducer,
    TodoIndexReducer,
    BackIndexReducer,
    AddFeedTagReducer,
    AddFeedTagSelectedReducer,
    AddFeedNotifReducer,
    GoalBackIndexReducer,
} from "./add_feed";
import {
    FocusDoneReducer,
    FocusInfoReducer,
    FocusTimeSetReducer,
} from "./focus_feed";
import {
    ChartDataReducer,
    MostFocusedReducer,
    TimerFeedReducer,
    TimerFeedTodayReducer,
    TimerFeedWeekReducer,
    ToggleReducer,
} from "./timer_feed";
import {
    ListCompleted,
    ListDefault,
    ListFeedReducer,
    ListImportant,
    ListInfo,
    ListTasks,
} from "./list_feed";
import {
    CompletedGoalsTimeoutReducer,
    FocusTimeoutReducer,
    GoalCompleteTimeoutReducer,
    GoalTimeoutReducer,
    HomeTimeoutReducer,
    ImportantCompleteTimeoutReducer,
    ListTimeoutReducer,
    ListViewTimeoutReducer,
    TaskCompleteTimeoutReducer,
} from "./timeouts";
import {
    EarlierCollapseReducer,
    TodayCollapseReducer,
    TomorrowCollapseReducer,
    YesterdayCollapseReducer,
    LaterCollapseReducer,
} from "./toggles";
import {
    GoalCompleteHeightReducer,
    GoalHeightReducer,
    HomeHeightReducer,
    ListHeightReducer,
    ListViewHeightReducer,
    SettingsHeightReducer,
    TimerHeightReducer,
} from "./scroll_height";
import {
    BatteryOptimisationsReducer,
    DonationItemsReducer,
    DonationMemberReducer,
    DonationReducer,
} from "./home_feed";

const allReducers = combineReducers({
    bottom_nav: bottom_nav,
    dark_mode: dark_mode,
    todos: AddTodosReducer,
    goals: AddGoalsReducer,
    addfeed_switch: AddFeedSwitchReducer,
    todo_desc: AddFeedTodoDescReducer,
    todo_steps: AddFeedStepsReducer,
    todo_list_option: AddFeedListReducer,
    todo_list_selected: AddFeedListSelectedReducer,
    todo_tag_option: AddFeedTagReducer,
    todo_tag_selected: AddFeedTagSelectedReducer,
    todo_due_date: AddFeedDueDateReducer,
    todo_remind_timestamp: AddFeedRemindReducer,
    todo_repeat_option: AddFeedRepeatReducer,
    goal_summary: AddFeedSummaryReducer,
    todo_notes_option: AddFeedNotesReducer,
    focus_info: FocusInfoReducer,
    focus_time_set: FocusTimeSetReducer,
    todo_complete_set: AddFeedCompleteSetReducer,
    todo_important_set: AddFeedImportantSetReducer,
    textarea_state: AddFeedTextareaReducer,
    completed_goals: GoalsFeedReducer,
    focus_done: FocusDoneReducer,
    focustime: AddFeedFocusTimeReducer,
    notif_state: AddFeedNotifReducer,
    url: AddFeedURLReducer,
    timer_feed: TimerFeedReducer,
    lists_feed: ListFeedReducer,
    list_info: ListInfo,
    list_tasks: ListTasks,
    users_lists: UsersListsReducer,
    default_: ListDefault,
    important_: ListImportant,
    completed_: ListCompleted,
    todo_index: TodoIndexReducer,
    back_index: BackIndexReducer,
    goal_timeout: GoalTimeoutReducer,
    home_timeout: HomeTimeoutReducer,
    list_timeout: ListTimeoutReducer,
    listview_timeout: ListViewTimeoutReducer,
    focus_timeout: FocusTimeoutReducer,
    collapse_earlier: EarlierCollapseReducer,
    collapse_yesterday: YesterdayCollapseReducer,
    collapse_today: TodayCollapseReducer,
    collapse_tomorrow: TomorrowCollapseReducer,
    collapse_later: LaterCollapseReducer,
    timer_feed_today: TimerFeedTodayReducer,
    timer_feed_week: TimerFeedWeekReducer,
    toggle: ToggleReducer,
    important_complete: ImportantCompleteTimeoutReducer,
    task_complete: TaskCompleteTimeoutReducer,
    goal_complete: GoalCompleteTimeoutReducer,
    most_focused: MostFocusedReducer,
    chart_data: ChartDataReducer,
    goal_index: GoalBackIndexReducer,
    completed_goals_timeout: CompletedGoalsTimeoutReducer,
    home_height: HomeHeightReducer,
    lists_height: ListHeightReducer,
    listview_height: ListViewHeightReducer,
    goals_height: GoalHeightReducer,
    goals_complete_height: GoalCompleteHeightReducer,
    timer_height: TimerHeightReducer,
    settings_height: SettingsHeightReducer,
    donation_modal: DonationReducer,
    donation: DonationItemsReducer,
    is_member: DonationMemberReducer,
    battery_opt: BatteryOptimisationsReducer,
});

export default allReducers;
